---
version: "3.9"

x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

services:
  ovos_gui_websocket:
    <<: *podman
    container_name: ovos_gui_websocket
    hostname: ovos_gui_websocket
    restart: unless-stopped
    image: docker.io/smartgic/ovos-gui-websocket:${VERSION}
    logging: *default-logging
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      - ovos_messagebus

  ovos_gui:
    <<: *podman
    container_name: ovos_gui
    hostname: ovos_gui
    restart: unless-stopped
    image: docker.io/smartgic/ovos-gui-shell:${VERSION}
    logging: *default-logging
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      DISPLAY: :0
      QT_QPA_PLATFORM: eglfs
    network_mode: host
    devices:
      - /dev/dri
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${OVOS_SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
    depends_on:
      - ovos_messagebus
      - ovos_gui_websocket
      - ovos_phal
